name: select-runs-on-action
description:
  takes inputs for repository and mapping file to dynamically select the runs-on
  runner
author: William Sanders

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  config-ref:
    description:
      Branch, tag, or commit SHA to fetch from in the config-repository
      (optional, defaults to default branch)
    required: false
  config-repository:
    description: GitHub repository name
    required: false
    default: veracode
  github-token:
    description: 'GitHub token with repo access to read the configuration file'
    required: true
  owner:
    description: GitHub repository owner
    required: true
  repository:
    description: GitHub repository name
    required: true
  veracode-team-mapping-yaml:
    description: YAML mapping file for runs-on configuration
    required: true
    default: 'team-mapping.yaml'

# Define your outputs here.
outputs:
  build-runs-on:
    description: Build runs_on runner selection from YAML mapping file
  default-runs-on:
    description: Default runs_on runner selection from YAML mapping file

runs:
  using: node24
  main: dist/index.js
