name: select-runs-on-action
description:
  takes inputs for repository and mapping file to dynamically select the runs-on
  runner
author: William Sanders

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  config-repository:
    description: GitHub repository name
    required: false
    default: veracode
  default-runs-on: # formatted as [ 'ubuntu-latest' ]
    description: Default runs_on value from veracode workflow inputs
    required: true
  github-token:
    description: 'GitHub token with repo access to read the configuration file'
    required: true
  owner:
    description: GitHub repository owner
    required: true
  ref:
    description:
      Branch, tag, or commit SHA to fetch from (optional, defaults to default
      branch)
    required: false
  repository:
    description: GitHub repository name
    required: true
  runs-on-mapping-yaml:
    description: YAML mapping file for runs-on configuration
    required: true
    default: 'runs-on-mapping.yaml'

# Define your outputs here.
outputs:
  runs-on:
    description: runs_on runner selection from YAML mapping file

runs:
  using: node24
  main: dist/index.js
