name: Build Dist
on: pull_request
jobs:
  build:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - run: npm ci && npm run bundle
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Rebuild dist files"
          file_pattern: "dist/*"
